version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test-unit:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - run:
        name: Install dependencies
        command: 'npm install'
      - run:
        name: Install JUnit coverage reporter
        command: npm install --save-dev jest-junit
      - run:
          name: unit test
          command: npm run test:unit --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/results.xml"
      - store_artifacts:
        path: test-results
        prefix: tests
      - store_test_results:
        path: test-results
  test-coverage:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - run:
        name: Install dependencies
        command: 'npm install'
      - run:
        name: code-coverage
        command: npm run test:coverage
      - store_artifacts:
        path: coverage
        prefix: coverage
workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test-unit
        - test-coverage